### ISSUE TITLE
Rubocopを入れる

### ISSUE THREAD

**Issue by ledsun** [lodqa/lodqa_email_agent#3]
# ゴール
```sh
bundle exec rubocop
```
で、rubocopのチェックが走るようにしてください。

# 参考情報

rubocopはチェックするルールを.rubocop.ymlを使って設定できます。

.rubocop.ymlは
```yml
Metrics/AbcSize:
  Max: 15

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 10

Style/Documentation:
  Exclude:
    - app/models/application_record.rb

AllCops:
  Exclude:
    - config.ru
    - Gemfile
    - Rakefile
    - bin/*
    - config/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
```

を参考にしてください。Railsの生成したファイルをチェック対称から除外しています。

以下のルールほ数値の調整が必要かもしれません。

- Metrics/AbcSize
- Metrics/LineLength
- Metrics/MethodLength

ルールの意味は https://rubocop.readthedocs.io/en/latest/cops_metrics/ を参考にしてください。
