### ISSUE TITLE
LODQA_BSをdocker-composeで起動する

### ISSUE THREAD

**Issue by ledsun** [lodqa/lodqa_email_agent#50]
docker-compose.ymlを作成する
```yml
version: '3'
services:
  lodqa_bs:
    build: https://github.com/lodqa/lodqa_bs.git
    ports:
      - 81:3000

  lodqa_email_agent:
    build: .
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/myapp
    env_file:
      - .env
    depends_on:
      - lodqa_bs
```

```
docker-compose build
```
が成功すること

```
docker-compose up
```
で、LODQA_BSとLODQA_EMAIL_AGENTが両方起動すること
